# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lappis
email: caguiar@unb.br / https://carlarocha.org
description: > # this means to ignore newlines until "baseurl:"
  Laboratório Avançado de Produção, Pesquisa & Inovação em Software.
baseurl:  # the subpath of your site, e.g. /blog
url: "https://lappis-unb.github.io/lappis.rocks/" # the base hostname & protocol for your site
github_username: lappis-unb
instagram_username: lab.livre
linkedin_username: lappis-rocks

address: |
  UnB | Universidade de Brasília
  FGA | Faculdade do gama
  LAPPIS | Laboratório Aplicado de Produção Pesquisa e Inovação em Software

emails: |
  caguiar@unb.br

# Build settings
markdown: kramdown
exclude: ["README.md"]


collections:
  sections:
    output: true
  lappis_members:
    output: true
  projects:
    output: true



theme: minima
plugins_dir:
  - jekyll-feed
