# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lappis
email: webmaster.fga@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Laboratório Avançado de Produção, Pesquisa & Inovação em Software.
baseurl:  # the subpath of your site, e.g. /blog
url: "https://lappis-unb.github.io/lappis.rocks/" # the base hostname & protocol for your site
twitter_username: lappisunb
github_username: lappis-unb
facebook_username: lappisunb5
instagram_username: lappisunb
medium_username: lappisunbfga

# Build settings
markdown: kramdown
exclude: ["README.md"]


collections:
  sections:
    output: true
  lappis_members:
    output: true
  projects:
    output: true



theme: minima
plugins_dir:
  - jekyll-feed
