apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: site-ing
  namespace: site-production
  annotations:  
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - www.lappis.rocks
    secretName: letsencrypt-prod
  rules:
  - host: www.lappis.rocks
    http:
      paths:
      - backend:
          serviceName: lappis-site-svc
          servicePort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: lappis-site-svc
  namespace: site-production
spec:
  selector:
    app: site
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: site-deployment
  namespace: site-production
  labels:
    app: site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: site
  template:
    metadata:
      labels:
        app: site
    spec:
      containers:
      - name: site
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 4000